//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace true_miner_control.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31")]
        public string save_textbox_dag {
            get {
                return ((string)(this["save_textbox_dag"]));
            }
            set {
                this["save_textbox_dag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("430")]
        public string save_textbox_equi {
            get {
                return ((string)(this["save_textbox_equi"]));
            }
            set {
                this["save_textbox_equi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string save_textbox_dag_link {
            get {
                return ((string)(this["save_textbox_dag_link"]));
            }
            set {
                this["save_textbox_dag_link"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string save_textbox_equi_link {
            get {
                return ((string)(this["save_textbox_equi_link"]));
            }
            set {
                this["save_textbox_equi_link"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public string save_textbox_W {
            get {
                return ((string)(this["save_textbox_W"]));
            }
            set {
                this["save_textbox_W"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1449")]
        public string save_textbox_prixW {
            get {
                return ((string)(this["save_textbox_prixW"]));
            }
            set {
                this["save_textbox_prixW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("168")]
        public string save_textbox_dag_decred {
            get {
                return ((string)(this["save_textbox_dag_decred"]));
            }
            set {
                this["save_textbox_dag_decred"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1680")]
        public string save_textbox_decred {
            get {
                return ((string)(this["save_textbox_decred"]));
            }
            set {
                this["save_textbox_decred"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("183")]
        public string save_textbox_dag_sia {
            get {
                return ((string)(this["save_textbox_dag_sia"]));
            }
            set {
                this["save_textbox_dag_sia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1830")]
        public string save_textbox_sia {
            get {
                return ((string)(this["save_textbox_sia"]));
            }
            set {
                this["save_textbox_sia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("173")]
        public string save_textbox_dag_lbry {
            get {
                return ((string)(this["save_textbox_dag_lbry"]));
            }
            set {
                this["save_textbox_dag_lbry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("165")]
        public string save_textbox_lbry {
            get {
                return ((string)(this["save_textbox_lbry"]));
            }
            set {
                this["save_textbox_lbry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1632")]
        public string save_textbox_pascal {
            get {
                return ((string)(this["save_textbox_pascal"]));
            }
            set {
                this["save_textbox_pascal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("163")]
        public string save_textbox_dag_pascal {
            get {
                return ((string)(this["save_textbox_dag_pascal"]));
            }
            set {
                this["save_textbox_dag_pascal"] = value;
            }
        }
    }
}
